player_app/urls.py
from django.urls import path
from . import views

app_name = 'player_app'

urlpatterns = [
    path("", views.search, name='search'),
    path("players", views.all_player, name="all_player"),
    path("result", views.result, name="result"),
    path("<int:uniform_number>_<str:player_name>", views.player_detail, name="player_info"),
    path("<int:uniform_number>_more_detail/", views.player_moreinfo, name="more_detail"),
    path("<int:uniform_number>/csv/", views.player_csv, name="player_csv"),
    path("register_user", views.register_user, name = "register_user"),
    path("login", views.login, name = "login"),
    path("register_original_batter/", views.register_original_batter, name = "register_original_batter"),
    path("register_original_pitcher/", views.register_original_pitcher, name = "register_original_pitcher"),
    path("original_all_player/", views.original_all_player, name = "original_all_player"),
    path("<int:uniform_number>/_more_detail", views.original_player_detail, name = "original_player_detail")
]



player_project/urls.py
from django.urls import path,include

urlpatterns = [
    path('', include('player_app.urls'))
]


player_app/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError

#ユーザー登録　メール必須
class CustomUserManager(BaseUserManager):
    def create_user(this, email: str, password=None, username=None, first_name=None):
        if not email:
            raise ValueError("メールアドレスは必須です")
        email = this.normalize_email(email)

        user = this.model(
            email=email,
            username=username,
            first_name=first_name,
        )
        user.set_password(password)   #ハッシュ化
        user.save() #userを更新
        return user


#User定義
class User(AbstractBaseUser, PermissionsMixin):
    user_id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=150, unique=True)
    email = models.EmailField(unique=True)  #認証に使うため重複不可とする
    first_name = models.CharField(max_length=150, blank=True, null=True) 
    last_name = models.CharField(max_length=150, blank=True, null=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    player_count = models.IntegerField(null=True)

    USERNAME_FIELD = "email"    #メールアドレス認証のため
    REQUIRED_FIELDS = ["username"]
    
    objects = CustomUserManager() 

    class Meta:
        db_table = "user"  
 
        


#選手用
class PlayerBase(models.Model):
    uniform_number = models.IntegerField(primary_key=True) 
    player_name = models.CharField(max_length=50)   
    birthday = models.DateField(null=True, blank=True)
    position = models.CharField(max_length=2)

    class Meta:
        abstract = True 

class Batter(PlayerBase):
    batting_hand = models.CharField(max_length=1)
    throwing_hand = models.CharField(max_length=1)
    
    class Meta:
        db_table = "batter"
        managed = False #SQLの学習のためmigrationsは一部自分で記述

class Pitcher(PlayerBase):
    throwing_hand = models.CharField(max_length=1)
    batting_hand = models.CharField(max_length=1)
    
    class Meta:
        db_table = "pitcher"
        managed = False


class Batting_status(models.Model): 
    uniform_number = models.OneToOneField( 
        Batter,
        db_column="uniform_number",
        on_delete=models.PROTECT,
        primary_key=True,
        related_name="battingstatus_player"
    )
    games = models.IntegerField(null=True, blank=True)
    numPlate = models.IntegerField(null=True, blank=True)
    numBat = models.IntegerField(null=True, blank=True)
    points = models.IntegerField(null=True, blank=True)
    hits = models.IntegerField(null=True, blank=True)
    hit2nd = models.IntegerField(null=True, blank=True)
    hit3rd = models.IntegerField(null=True, blank=True)
    homeruns = models.IntegerField(null=True, blank=True)
    baseHits = models.IntegerField(null=True, blank=True)
    getpoint = models.IntegerField(null=True, blank=True)
    steal = models.IntegerField(null=True, blank=True)
    missedSteal = models.IntegerField(null=True, blank=True)
    bants = models.IntegerField(null=True, blank=True)
    sacFry = models.IntegerField(null=True, blank=True)
    fourballs = models.IntegerField(null=True, blank=True)
    intWalk = models.IntegerField(null=True, blank=True)
    deadballs = models.IntegerField(null=True, blank=True)
    strikeOut = models.IntegerField(null=True, blank=True)
    doublePlay = models.IntegerField(null=True, blank=True)
    errors = models.IntegerField(null=True, blank=True)
    
    class Meta:
        db_table = "batting_status"
        managed = False


class Pitching_status(models.Model):    
    uniform_number = models.OneToOneField( 
        Pitcher,
        db_column="uniform_number",
        on_delete=models.PROTECT,
        primary_key=True,
        related_name="pitchingstatus_player"
    )
    games = models.IntegerField(null=True, blank=True)
    win = models.IntegerField(null=True, blank=True)
    lose = models.IntegerField(null=True, blank=True)
    saves = models.IntegerField(null=True, blank=True)
    hold = models.IntegerField(null=True, blank=True)
    hp = models.IntegerField(null=True, blank=True)
    fullIning = models.IntegerField(null=True, blank=True)
    perfect = models.IntegerField(null=True, blank=True)
    noFour = models.IntegerField(null=True, blank=True)
    batter = models.IntegerField(null=True, blank=True)
    ining = models.IntegerField(null=True, blank=True)
    hit = models.IntegerField(null=True, blank=True)
    homerun = models.IntegerField(null=True, blank=True)
    fourball = models.IntegerField(null=True, blank=True)
    int_Walk = models.IntegerField(null=True, blank=True)
    deadBall = models.IntegerField(null=True, blank=True)
    strikeOut = models.IntegerField(null=True, blank=True)
    wildPitch = models.IntegerField(null=True, blank=True)
    balk = models.IntegerField(null=True, blank=True)
    lostScore = models.IntegerField(null=True, blank=True)
    earnedRun = models.IntegerField(null=True, blank=True)
    ERA = models.FloatField(null=True, blank=True)  
    QS = models.IntegerField(null=True, blank=True)
    
    class Meta:
        db_table = "pitching_status"
        managed = False
        


#オリジナル選手

class User_player(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        to_field="user_id",
        on_delete=models.CASCADE,
        related_name="%(class)ss", 
    )
    uniform_number = models.IntegerField()
    player_name = models.CharField(max_length=50)
    birthday = models.DateField(null=True, blank=True)
    position = models.CharField(max_length=2)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_public = models.BooleanField(default=False, help_text="他ユーザーに公開しますか")

    class Meta:
        abstract = True
        ordering = ["user", "uniform_number"]


class User_batter(User_player):
    batting_hand = models.CharField(max_length=1, blank=True, null=True)
    throwing_hand = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        db_table = "user_batter"
        #同一ユーザー内での背番号の一意性を保つ
        unique_together = (("user", "uniform_number"),)
        indexes = [
            models.Index(fields=["user", "uniform_number"]),
            models.Index(fields=["player_name"]),
        ]
        managed = False

    @classmethod
    def create_batter(cls, user, uniform_number, player_name, 
                       games, numPlate, numBat, points, hits, hit2nd, hit3rd,
                       homeruns, baseHits, getpoint, steal, missedSteal, bants,
                       sacFry, fourballs, intWalk, deadballs, strikeOut, doublePlay, errors,
                       birthday=None, position=None, batting_hand=None, throwing_hand=None):
        #重複確認
        if cls.objects.filter(user=user, uniform_number=uniform_number).exists():
            raise ValidationError(f"背番号 {uniform_number} は既に使用されています。")
        if cls.objects.filter(user=user, player_name=player_name).exists():
            raise ValidationError(f"選手名 {player_name} は既に存在します。")

        return cls.objects.create(
            user=user,
            uniform_number=uniform_number,
            player_name=player_name,
            birthday=birthday,
            position=position,
            batting_hand=batting_hand,
            throwing_hand=throwing_hand,
            games=games,
            numPlate=numPlate,
            numBat=numBat,
            points=points,
            hits=hits,
            hit2nd=hit2nd,
            hit3rd=hit3rd,
            homeruns=homeruns,
            baseHits=baseHits,
            getpoint=getpoint,
            steal=steal,
            missedSteal=missedSteal ,
            bants=bants,
            sacFry=sacFry,
            fourballs=fourballs,
            intWalk=intWalk,
            deadballs=deadballs,
            strikeOut=strikeOut,
            doublePlay=doublePlay,
            errors=errors,
        )

class User_pitcher(User_player):
    throwing_hand = models.CharField(max_length=1, blank=True, null=True)
    batting_hand = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        db_table = "user_pitcher"
        unique_together = (("user", "uniform_number"),)
        indexes = [
            models.Index(fields=["user", "uniform_number"]),
            models.Index(fields=["player_name"]),
        ]
        managed = False

    @classmethod
    def create_pitcher(cls, user, uniform_number, player_name,
                   birthday, position, games, win, lose, saves, hold, hp,
                   fullIning, perfect, noFour, batter, ining,
                   hit, homerun, fourball, intWalk, deadBall,
                   strikeOut, wildPitch, balk, lostScore,
                   earnedRun, ERA, QS, batting_hand=None, throwing_hand=None,):
        if cls.objects.filter(user=user, uniform_number=uniform_number).exists():
            raise ValidationError(f"背番号 {uniform_number} は既に使用されています。")
        if cls.objects.filter(user=user, player_name=player_name).exists():
            raise ValidationError(f"選手名 {player_name} は既に存在します。")

        return cls.objects.create(
            user=user,
            uniform_number=uniform_number,
            player_name=player_name,
            birthday=birthday,
            position=position,
            batting_hand=batting_hand,
            throwing_hand=throwing_hand,
            games=games,
            win=win,
            lose=lose,
            saves=saves,
            hold=hold,
            hp=hp,
            fullIning=fullIning,
            perfect=perfect,
            noFour=noFour,

player_app/forms.py
from django import forms

#自動バリデーションのため定義を合わせる

#選手検索
class Search_player:
    name = forms.CharField()
    
#ユーザー登録
class Register_user(forms.Form):
    username = forms.CharField(label="ユーザー名")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput)
    email = forms.EmailField(label="メールアドレス")
    first_name = forms.CharField(required=False, label="ニックネーム")
    
#ログイン用
class Login(forms.Form):
    email = forms.EmailField(label="メールアドレス")
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput)

#オリジナル打者登録
class Register_original_batter(forms.Form):
    uniform_number = forms.IntegerField(label="背番号")
    player_name = forms.CharField(label="選手名")
    games = forms.IntegerField(label="試合数")
    numPlate = forms.IntegerField(label="打席数")
    numBat = forms.IntegerField(label="打数")
    points = forms.IntegerField(label="得点")
    hits = forms.IntegerField(label="安打数")
    hit2nd = forms.IntegerField(label="二塁打")
    hit3rd = forms.IntegerField(label="三塁打")
    homeruns = forms.IntegerField(label="本塁打")
    baseHits = forms.IntegerField(label="塁打数")
    getpoint = forms.IntegerField(label="打点")
    steal = forms.IntegerField(label="盗塁")
    missedSteal = forms.IntegerField(label="盗塁死")
    bants = forms.IntegerField(label="犠打")
    sacFry = forms.IntegerField(label="犠飛")
    fourballs = forms.IntegerField(label="四球")
    intWalk = forms.IntegerField(label="敬遠")
    deadballs = forms.IntegerField(label="死球")
    strikeOut = forms.IntegerField(label="三振")
    doublePlay = forms.IntegerField(label="併殺打")
    errors = forms.IntegerField(label="失策")
    birthday = forms.DateField(required=False, label="生年月日", widget=forms.DateInput(attrs={'type': 'date'}))
    position = forms.CharField(label="守備位置", max_length=1)
    batting_hand = forms.CharField(required=False, label="打ち手", max_length=1)
    throwing_hand = forms.CharField(required=False, label="投げ手", max_length=1)
        
#オリジナル投手登録
class Register_original_pitcher(forms.Form):
    uniform_number = forms.IntegerField(label="背番号")
    player_name = forms.CharField(label="選手名")
    birthday = forms.DateField(required=False, label="生年月日", widget=forms.DateInput(attrs={'type': 'date'}))
    position = forms.CharField(label="守備位置", max_length=1)
    games = forms.IntegerField(label="試合数")
    win = forms.IntegerField(label="勝利")
    lose = forms.IntegerField(label="敗北")
    saves = forms.IntegerField(label="セーブ")
    hold = forms.IntegerField(label="ホールド")
    hp = forms.IntegerField(label="HP")
    fullIning = forms.IntegerField(label="完投")
    perfect = forms.IntegerField(label="完封")
    noFour = forms.IntegerField(label="無四死球")
    batter = forms.IntegerField(label="対戦打者数")
    ining = forms.IntegerField(label="投球回")
    hit = forms.IntegerField(label="被安打")
    homerun = forms.IntegerField(label="被本塁打")
    fourball = forms.IntegerField(label="与四球")
    intWalk = forms.IntegerField(label="敬遠")
    deadBall = forms.IntegerField(label="与死球")
    strikeOut = forms.IntegerField(label="奪三振")
    wildPitch = forms.IntegerField(label="暴投")
    balk = forms.IntegerField(label="ボーク")
    lostScore = forms.IntegerField(label="失点")
    earnedRun = forms.IntegerField(label="自責点")
    ERA = forms.FloatField(label="防御率")
    QS = forms.IntegerField(label="QS")
    batting_hand = forms.CharField(required=False, label="打ち手", max_length=1)
    throwing_hand = forms.CharField(required=False, label="投げ手", max_length=1)


templates/all_player.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>選手一覧</title>
</head>

<h1>選手一覧</h1>
<table class="status">
    <tr>
        <th>背番号</th>
        <th>名前</th>
        <th>詳細</th>
        <th>CSV</th>
    </tr>
    {% for value in player %}
    <tr>
        <td>{{ value.uniform_number }}</td>
        <td>{{ value.player_name }}</td>
        <td>
            <a href="{% url 'player_app:player_info' uniform_number=value.uniform_number player_name=value.player_name %}">
                個人ページ
            </a>
        </td>
        <td>
            <a href="{% url 'player_app:player_csv' uniform_number=value.uniform_number %}">ダウンロード</a>
        </td>
    </tr>
    {% endfor %}
</table>
<p><a href="{% url 'player_app:search'%}">TOPへ戻る</a></p>
</html>

<style>

table.status {
    border-collapse: collapse; 
    width: 100%;
}

table.status th,
table.status td {
    border: 1px solid black;   
    padding: 5px;              
    text-align: center;        
}
 
</style>

templates/register_original_pitcher.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Register_original_pitcher</title>
    </head>
    <body>
        <main>
            <div class="card">
            <h1>オリジナル投手登録画面</h1>
            <form method="post">
                {% csrf_token %}

                <ul>
                    <li><label for="id_uniform_number">背番号</label>
                        <input type="number" name="uniform_number" id="id_uniform_number" value="{{ form_register_pitcher.uniform_number.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.uniform_number.errors %}
                        <div class="error">{{ form_register_pitcher.uniform_number.errors }}</div>
                    {% endif %}

                    <li><label for="id_player_name">選手名</label>
                        <input type="text" name="player_name" id="id_player_name" value="{{ form_register_pitcher.player_name.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.player_name.errors %}
                        <div class="error">{{ form_register_pitcher.player_name.errors }}</div>
                    {% endif %}

                    <li><label for="id_birthday">生年月日</label>
                        <input type="date" name="birthday" id="id_birthday" value="{{ form_register_pitcher.birthday.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.birthday.errors %}
                        <div class="error">{{ form_register_pitcher.birthday.errors }}</div>
                    {% endif %}

                    <li><label for="id_position">守備位置</label>
                        <input type="text" name="position" id="id_position" maxlength="1" value="{{ form_register_pitcher.position.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.position.errors %}
                        <div class="error">{{ form_register_pitcher.position.errors }}</div>
                    {% endif %}

                    <li><label for="id_batting_hand">打ち手</label>
                        <input type="text" name="batting_hand" id="id_batting_hand" maxlength="1" value="{{ form_register_pitcher.batting_hand.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.batting_hand.errors %}
                        <div class="error">{{ form_register_pitcher.batting_hand.errors }}</div>
                    {% endif %}

                    <li><label for="id_throwing_hand">投げ手</label>
                        <input type="text" name="throwing_hand" id="id_throwing_hand" maxlength="1" value="{{ form_register_pitcher.throwing_hand.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.throwing_hand.errors %}
                        <div class="error">{{ form_register_pitcher.throwing_hand.errors }}</div>
                    {% endif %}

                    <li><label for="id_games">登板数</label>
                        <input type="number" name="games" id="id_games" value="{{ form_register_pitcher.games.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.games.errors %}
                        <div class="error">{{ form_register_pitcher.games.errors }}</div>
                    {% endif %}

                    <li><label for="id_win">勝利</label>
                        <input type="number" name="win" id="id_win" value="{{ form_register_pitcher.win.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.win.errors %}
                        <div class="error">{{ form_register_pitcher.win.errors }}</div>
                    {% endif %}

                    <li><label for="id_lose">敗北</label>
                        <input type="number" name="lose" id="id_lose" value="{{ form_register_pitcher.lose.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.lose.errors %}
                        <div class="error">{{ form_register_pitcher.lose.errors }}</div>
                    {% endif %}

                    <li><label for="id_saves">セーブ</label>
                        <input type="number" name="saves" id="id_saves" value="{{ form_register_pitcher.saves.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.saves.errors %}
                        <div class="error">{{ form_register_pitcher.saves.errors }}</div>
                    {% endif %}

                    <li><label for="id_hold">ホールド</label>
                        <input type="number" name="hold" id="id_hold" value="{{ form_register_pitcher.hold.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.hold.errors %}
                        <div class="error">{{ form_register_pitcher.hold.errors }}</div>
                    {% endif %}

                    <li><label for="id_hp">HP</label>
                        <input type="number" name="hp" id="id_hp" value="{{ form_register_pitcher.hp.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.hp.errors %}
                        <div class="error">{{ form_register_pitcher.hp.errors }}</div>
                    {% endif %}

                    <li><label for="id_fullIning">完投</label>
                        <input type="number" name="fullIning" id="id_fullIning" value="{{ form_register_pitcher.fullIning.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.fullIning.errors %}
                        <div class="error">{{ form_register_pitcher.fullIning.errors }}</div>
                    {% endif %}

                    <li><label for="id_perfect">完封</label>
                        <input type="number" name="perfect" id="id_perfect" value="{{ form_register_pitcher.perfect.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.perfect.errors %}
                        <div class="error">{{ form_register_pitcher.perfect.errors }}</div>
                    {% endif %}

                    <li><label for="id_noFour">無四球</label>
                        <input type="number" name="noFour" id="id_noFour" value="{{ form_register_pitcher.noFour.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.noFour.errors %}
                        <div class="error">{{ form_register_pitcher.noFour.errors }}</div>
                    {% endif %}

                    <li><label for="id_batter">打者数</label>
                        <input type="number" name="batter" id="id_batter" value="{{ form_register_pitcher.batter.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.batter.errors %}
                        <div class="error">{{ form_register_pitcher.batter.errors }}</div>
                    {% endif %}

                    <li><label for="id_ining">投球回</label>
                        <input type="number" name="ining" id="id_ining" value="{{ form_register_pitcher.ining.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.ining.errors %}
                        <div class="error">{{ form_register_pitcher.ining.errors }}</div>
                    {% endif %}

                    <li><label for="id_hit">被安打</label>
                        <input type="number" name="hit" id="id_hit" value="{{ form_register_pitcher.hit.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.hit.errors %}
                        <div class="error">{{ form_register_pitcher.hit.errors }}</div>
                    {% endif %}

                    <li><label for="id_homerun">被本塁打</label>
                        <input type="number" name="homerun" id="id_homerun" value="{{ form_register_pitcher.homerun.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.homerun.errors %}
                        <div class="error">{{ form_register_pitcher.homerun.errors }}</div>
                    {% endif %}

                    <li><label for="id_fourball">与四球</label>
                        <input type="number" name="fourball" id="id_fourball" value="{{ form_register_pitcher.fourball.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.fourball.errors %}
                        <div class="error">{{ form_register_pitcher.fourball.errors }}</div>
                    {% endif %}

                    <li><label for="id_int_Walk">敬遠</label>
                        <input type="number" name="int_Walk" id="id_int_Walk" value="{{ form_register_pitcher.int_Walk.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.int_Walk.errors %}
                        <div class="error">{{ form_register_pitcher.int_Walk.errors }}</div>
                    {% endif %}

                    <li><label for="id_deadBall">死球</label>
                        <input type="number" name="deadBall" id="id_deadBall" value="{{ form_register_pitcher.deadBall.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.deadBall.errors %}
                        <div class="error">{{ form_register_pitcher.deadBall.errors }}</div>
                    {% endif %}

                    <li><label for="id_strikeOut">奪三振</label>
                        <input type="number" name="strikeOut" id="id_strikeOut" value="{{ form_register_pitcher.strikeOut.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.strikeOut.errors %}
                        <div class="error">{{ form_register_pitcher.strikeOut.errors }}</div>
                    {% endif %}

                    <li><label for="id_wildPitch">暴投</label>
                        <input type="number" name="wildPitch" id="id_wildPitch" value="{{ form_register_pitcher.wildPitch.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.wildPitch.errors %}
                        <div class="error">{{ form_register_pitcher.wildPitch.errors }}</div>
                    {% endif %}

                    <li><label for="id_balk">ボーク</label>
                        <input type="number" name="balk" id="id_balk" value="{{ form_register_pitcher.balk.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.balk.errors %}
                        <div class="error">{{ form_register_pitcher.balk.errors }}</div>
                    {% endif %}

                    <li><label for="id_lostScore">失点</label>
                        <input type="number" name="lostScore" id="id_lostScore" value="{{ form_register_pitcher.lostScore.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.lostScore.errors %}
                        <div class="error">{{ form_register_pitcher.lostScore.errors }}</div>
                    {% endif %}

                    <li><label for="id_earnedRun">自責点</label>
                        <input type="number" name="earnedRun" id="id_earnedRun" value="{{ form_register_pitcher.earnedRun.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.earnedRun.errors %}
                        <div class="error">{{ form_register_pitcher.earnedRun.errors }}</div>
                    {% endif %}

                    <li><label for="id_ERA">防御率</label>
                        <input type="number" step="0.01" name="ERA" id="id_ERA" value="{{ form_register_pitcher.ERA.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.ERA.errors %}
                        <div class="error">{{ form_register_pitcher.ERA.errors }}</div>
                    {% endif %}

                    <li><label for="id_QS">QS</label>
                        <input type="number" name="QS" id="id_QS" value="{{ form_register_pitcher.QS.value|default_if_none:'' }}"></li>
                    {% if form_register_pitcher.QS.errors %}
                        <div class="error">{{ form_register_pitcher.QS.errors }}</div>
                    {% endif %}
                </ul>

                <button type="submit">登録</button>
            </form>
            </div>

            <p><a href="{% url 'player_app:search' %}">TOPへ戻る</a></p>
        </main>
    </body>
</html>

<style>
ul {
    list-style-type: none;       
}

.card {
    border: 1px solid #ccc;
    padding: 15px;
    margin: 10px 0;
    border-radius: 8px;
    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);
    background-color: #fff9efff;
}
</style>

templates/result.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Player_result</title>
</head>
<body>

    <header>
    <h1>検索結果一覧</h1>
    </header>
    <main>
    {% if players %}
   <table class="status">
    <tr>
        <th>背番号</th>
        <th>名前</th>
        <th>詳細</th>
        <th>CSV</th>
    </tr>
    {% for player in players %}
    <tr>
        <td>{{ player.uniform_number }}</td>
        <td>{{ player.player_name }}</td>
        <td>
            <a href="{% url 'player_app:player_info' uniform_number=player.uniform_number player_name=player.player_name %}">
                個人ページ
            </a>
        </td>
        <td>
            <a href="{% url 'player_app:player_csv' uniform_number=player.uniform_number %}">ダウンロード</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% elif name %}
    <p>「{{ name }}」に一致する選手は見つかりませんでした。</p>
{% else %}
    <p>検索ワードを入力してください。</p>
{% endif %}

<p><a href="{% url 'player_app:search'%}">TOPへ戻る</a></p>
    </main>
</body>

</html>

<style>

table.status {
    border-collapse: collapse; 
    width: 100%;
}

table.status th,
table.status td {
    border: 1px solid black;   
    padding: 5px;              
    text-align: center;        
}
 
</style>

templates/search.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Player_Search</title>
</head>
<body>

    <header>
    <h1>横浜DeNAベイスターズ 選手成績・指標検索</h1>
    </header>

    <main>
    <div class="card">
    <h2>選手検索</h2>
    <form method="POST" action="{% url 'player_app:result'%}">
    {% csrf_token %}

    <ul>
    <li><label for="id_searchplayer">検索したい選手の名前を入力してください(一部でも可)</label>
    <input type="text" name="player_name" id="id_searchplayer" value="{{name|default:''}}"></li>
    </ul>
    <input type="submit" value="検索">
    </form>
    </div>
    <p><a href="{% url 'player_app:all_player'%}">選手一覧はこちら</a></p>
    <p><a href="{% url 'player_app:login'%}">ログインはこちら</a></p> 
    <p><a href="{% url 'player_app:register_user'%}">ユーザー登録はこちら</a></p> 
    <p><a href="{% url 'player_app:register_original_batter'%}">オリジナル打者登録はこちら</a></p> 
    <p><a href="{% url 'player_app:register_original_pitcher'%}">オリジナル投手登録はこちら</a></p> 
    <p><a href="{% url 'player_app:original_all_player'%}">オリジナル選手一覧はこちら</a></p> 

    </main>
</body>
</html>

<style>
ul {
    list-style-type: none;       
}

.card {
    border: 1px solid #ccc;
    padding: 15px;
    margin: 10px 0;
    border-radius: 8px;
    box-shadow: 2px 2px 5px rgba(0,0,0,0.3);
    background-color: #fff9efff;
    }
</style>

